"""add source.note

Revision ID: 19ad970da1bf
Revises: 2f20de75eb2f
Create Date: 2026-07-21 07:43:47.944575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ad970da1bf'
down_revision: Union[str, None] = '2f20de75eb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'note')
    # ### end Alembic commands ###
