"""add source attendees

Revision ID: 5dda47f6a3cf
Revises: 4531afc5fe35
Create Date: 2026-07-22 04:40:38.807346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dda47f6a3cf'
down_revision: Union[str, None] = '4531afc5fe35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('attendees', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'attendees')
    # ### end Alembic commands ###
