"""add project.active

Revision ID: 6c6edff4d2b5
Revises: 7b5ccd12e977
Create Date: 2026-07-21 05:40:21.543837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6edff4d2b5'
down_revision: Union[str, None] = '7b5ccd12e977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'active')
    # ### end Alembic commands ###
