"""add action_item.due_date

Revision ID: 7b5ccd12e977
Revises: c4f1e8fe807d
Create Date: 2026-07-21 05:16:00.631055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5ccd12e977'
down_revision: Union[str, None] = 'c4f1e8fe807d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_items', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_items', 'due_date')
    # ### end Alembic commands ###
